### ISSUE TITLE
Change .travis.yml so that jobs run on their new container based infra

### ISSUE THREAD

**Issue by edmorley** [hwine/cookiecutter-pylibrary-minimal#1]
Travis have a newer container based stack that runs on EC2, that is both faster & allows the use of extra features (such as dependency caching):
http://docs.travis-ci.com/user/workers/container-based-infrastructure/

To use it, |sudo: false| must be set.

This has been done on the upstream of the upstream of this repo already:
https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/.travis.yml#L3

**Comment by hwine** [comment]
Sorry for long delay in noticing -- are you suggesting pulling that one feature in, or merging from upstream?

**Comment by edmorley** [comment]
> Sorry for long delay in noticing -- are you suggesting pulling that one feature in, or merging from upstream?

Either, upstream added it on my request:
https://github.com/ionelmc/cookiecutter-pylibrary-minimal/commit/521b160ca52b93b0db01168761f8ded57f7f9675
